services:
  - type: web
    name: render-http-header-test
    env: static
    staticPublishPath: ./
    headers:
      - path: /*
        name: x-render-test-1
        value: 1
      - path: /assets/theme.css
        name: x-render-test-2
        value: 2
      - path: /blog/*
        name: x-render-test-3
        value: 3
      - path: /**/*
        name: x-render-test-4
        value: 4
      - path: /*.css
        name: x-render-test-5
        value: 5
      - path: /**/*.css
        name: x-render-test-6
        value: 6
